"""
tools/pfz_tools.py — Potential Fishing Zone (PFZ) data layer.

DESIGN PRINCIPLE:
    Pure data / computation module — no AI calls, no Streamlit.
    Provides the structured PFZ dataset and the spatial query functions
    that the PFZ Agent consumes.

DATA SOURCE (mock):
    Zone coordinates, species, and depth data are modelled after real
    INCOIS (Indian National Centre for Ocean Information Services)
    PFZ advisories. In production, these would be replaced by a live
    INCOIS API call or a daily-downloaded GeoJSON feed.

Functions exported:
    get_all_zones()                            → full PFZ database
    find_nearest_zones(lat, lon, n, max_km)    → n closest zones
    haversine_km(lat1, lon1, lat2, lon2)       → great-circle distance
"""

import math
from typing import Optional


# ─────────────────────────────────────────────────────────────────────────────
# Haversine great-circle distance
# ─────────────────────────────────────────────────────────────────────────────

def haversine_km(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """
    Compute the straight-line distance (great-circle) between two GPS points.

    Formula: Haversine — numerically stable for short and long distances.
    Accuracy: within ~0.5% for distances up to 20,000 km.

    Args:
        lat1, lon1: Starting point (decimal degrees).
        lat2, lon2: Destination point (decimal degrees).

    Returns:
        Distance in kilometres (float).
    """
    R = 6371.0                           # Earth's mean radius (km)
    φ1, φ2 = math.radians(lat1), math.radians(lat2)
    Δφ     = math.radians(lat2 - lat1)
    Δλ     = math.radians(lon2 - lon1)
    a = (math.sin(Δφ / 2) ** 2
         + math.cos(φ1) * math.cos(φ2) * math.sin(Δλ / 2) ** 2)
    return R * 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))


# ─────────────────────────────────────────────────────────────────────────────
# PFZ Database — Comprehensive Coastal Coverage (70 Harbors & Zones)
# ─────────────────────────────────────────────────────────────────────────────
# Each record provides both the ISRO SIH schema (id, name, lat, lon, depth, species, status)
# and backward-compatible fields (zone_id, depth_m, quality, advisory, region, best_season).

PFZ_DATABASE: list[dict] = [

    # ═════════════════════════════════════════════════════════════════════════
    # 1. KARNATAKA COAST (Focus Region: Kundapura, Malpe, Udupi, Karwar, etc.)
    # ═════════════════════════════════════════════════════════════════════════
    {
        "id":                     "PFZ-KA-001",
        "zone_id":                "PFZ-KA-001",
        "name":                   "Mangaluru Old Port / Bunder Coastal Shelf",
        "lat":                    12.8500,
        "lon":                    74.7500,
        "depth":                  28,
        "depth_m":                28,
        "species":                "Indian Mackerel, Oil Sardine, Seer Fish",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 10,
        "advisory":               "Consistent coastal upwelling cell near Netravati mouth. High sardine CPUE.",
        "region":                 "Karnataka",
        "best_season":            "Aug–Dec",
    },
    {
        "id":                     "PFZ-KA-002",
        "zone_id":                "PFZ-KA-002",
        "name":                   "Gangolli / Kundapura Inshore Bank",
        "lat":                    13.6350,
        "lon":                    74.6200,
        "depth":                  25,
        "depth_m":                25,
        "species":                "Indian Mackerel, Oil Sardine, Prawns",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 8,
        "advisory":               "Panchagangavalli estuarine confluence generates high phytoplankton biomass.",
        "region":                 "Karnataka",
        "best_season":            "Sep–Feb",
    },
    {
        "id":                     "PFZ-KA-003",
        "zone_id":                "PFZ-KA-003",
        "name":                   "Kundapura Offshore Upwelling Zone",
        "lat":                    13.6100,
        "lon":                    74.4800,
        "depth":                  42,
        "depth_m":                42,
        "species":                "Yellow-fin Tuna, Ribbon Fish, Squid",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 24,
        "advisory":               "Shelf break divergence. Outstanding night squid jigging & pelagic drift.",
        "region":                 "Karnataka",
        "best_season":            "Oct–Mar",
    },
    {
        "id":                     "PFZ-KA-004",
        "zone_id":                "PFZ-KA-004",
        "name":                   "Malpe Harbor Deep-Water Trawl Grounds",
        "lat":                    13.3500,
        "lon":                    74.5800,
        "depth":                  35,
        "depth_m":                35,
        "species":                "Silver Pomfret, Squid, Cuttlefish, Threadfin Bream",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 14,
        "advisory":               "Major multi-day mechanized harbor bank. Prime trawl grounds.",
        "region":                 "Karnataka",
        "best_season":            "Sep–May",
    },
    {
        "id":                     "PFZ-KA-005",
        "zone_id":                "PFZ-KA-005",
        "name":                   "Malpe Outer Continental Shelf",
        "lat":                    13.3200,
        "lon":                    74.3500,
        "depth":                  55,
        "depth_m":                55,
        "species":                "Skipjack Tuna, King Mackerel, Barracuda",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 38,
        "advisory":               "Deep pelagic zone. Sea surface temperature fronts indicate dense fish aggregation.",
        "region":                 "Karnataka",
        "best_season":            "Nov–Apr",
    },
    {
        "id":                     "PFZ-KA-006",
        "zone_id":                "PFZ-KA-006",
        "name":                   "Udupi St. Mary's Coastal Zone",
        "lat":                    13.3800,
        "lon":                    74.6500,
        "depth":                  22,
        "depth_m":                22,
        "species":                "Crab, Croaker, Indian Mackerel, Anchovy",
        "status":                 "MEDIUM",
        "quality":                "MEDIUM",
        "distance_from_shore_km": 6,
        "advisory":               "Columnar basalt shoals provide rich benthic habitat. Artisanal gillnet zone.",
        "region":                 "Karnataka",
        "best_season":            "Oct–Feb",
    },
    {
        "id":                     "PFZ-KA-007",
        "zone_id":                "PFZ-KA-007",
        "name":                   "Kaup Light Reef Bank",
        "lat":                    13.2200,
        "lon":                    74.6800,
        "depth":                  20,
        "depth_m":                20,
        "species":                "Reef Cod, Snapper, Lobster, Sardine",
        "status":                 "MEDIUM",
        "quality":                "MEDIUM",
        "distance_from_shore_km": 7,
        "advisory":               "Submerged rocky ridges. Hook-and-line and traditional motorized craft recommended.",
        "region":                 "Karnataka",
        "best_season":            "Nov–Mar",
    },
    {
        "id":                     "PFZ-KA-008",
        "zone_id":                "PFZ-KA-008",
        "name":                   "Honnavar Sharavathi Estuarine Ridge",
        "lat":                    14.2800,
        "lon":                    74.3800,
        "depth":                  26,
        "depth_m":                26,
        "species":                "Prawns, Pomfret, Indian Mackerel, Mullet",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 8,
        "advisory":               "Sharavathi river plume enriches coastal shelf with high nutrient flux.",
        "region":                 "Karnataka",
        "best_season":            "Sep–Jan",
    },
    {
        "id":                     "PFZ-KA-009",
        "zone_id":                "PFZ-KA-009",
        "name":                   "Honnavar Offshore Pelagic Corridor",
        "lat":                    14.2500,
        "lon":                    74.1800,
        "depth":                  48,
        "depth_m":                48,
        "species":                "Seer Fish, Black Pomfret, Tuna",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 28,
        "advisory":               "Strong thermocline gradient at 35m. High pelagic fish density.",
        "region":                 "Karnataka",
        "best_season":            "Oct–Mar",
    },
    {
        "id":                     "PFZ-KA-010",
        "zone_id":                "PFZ-KA-010",
        "name":                   "Bhatkal Harbor Offshore Shoal",
        "lat":                    13.9750,
        "lon":                    74.5000,
        "depth":                  24,
        "depth_m":                24,
        "species":                "Oil Sardine, Mackerel, Sole Fish",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 6,
        "advisory":               "Shallow sandy-mud bank. Outstanding ring seine & gillnet yields.",
        "region":                 "Karnataka",
        "best_season":            "Aug–Dec",
    },
    {
        "id":                     "PFZ-KA-011",
        "zone_id":                "PFZ-KA-011",
        "name":                   "Murudeshwar Coastal Reef & Island Ground",
        "lat":                    14.0950,
        "lon":                    74.4400,
        "depth":                  22,
        "depth_m":                22,
        "species":                "Grouper, Coral Bream, Cuttlefish",
        "status":                 "MEDIUM",
        "quality":                "MEDIUM",
        "distance_from_shore_km": 5,
        "advisory":               "Netrani island approach corridor. Rich rocky bottom biodiversity.",
        "region":                 "Karnataka",
        "best_season":            "Oct–Feb",
    },
    {
        "id":                     "PFZ-KA-012",
        "zone_id":                "PFZ-KA-012",
        "name":                   "Kumta Aghanashini Shelf Grounds",
        "lat":                    14.4200,
        "lon":                    74.3400,
        "depth":                  25,
        "depth_m":                25,
        "species":                "White Prawns, Mud Crab, Silver Sillago, Mackerel",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 8,
        "advisory":               "Aghanashini estuary output creates perennial chlorophyll bloom.",
        "region":                 "Karnataka",
        "best_season":            "Sep–Jan",
    },
    {
        "id":                     "PFZ-KA-013",
        "zone_id":                "PFZ-KA-013",
        "name":                   "Tadadi Port Offshore Corridor",
        "lat":                    14.5100,
        "lon":                    74.2800,
        "depth":                  32,
        "depth_m":                32,
        "species":                "Ribbon Fish, Pomfret, Indian Anchovy",
        "status":                 "MEDIUM",
        "quality":                "MEDIUM",
        "distance_from_shore_km": 12,
        "advisory":               "Natural fishing harbor mouth. Active motorized traditional fleet sector.",
        "region":                 "Karnataka",
        "best_season":            "Oct–Feb",
    },
    {
        "id":                     "PFZ-KA-014",
        "zone_id":                "PFZ-KA-014",
        "name":                   "Karwar Deep-Water Ridge Zone",
        "lat":                    14.8800,
        "lon":                    73.8000,
        "depth":                  80,
        "depth_m":                80,
        "species":                "Tuna, Kingfish, Deep Sea Prawns",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 38,
        "advisory":               "Submarine ridge creates massive upwelling aggregation. Early morning optimal.",
        "region":                 "Karnataka",
        "best_season":            "Oct–Feb",
    },
    {
        "id":                     "PFZ-KA-015",
        "zone_id":                "PFZ-KA-015",
        "name":                   "Karwar Baithkol Harbor Coastal Grounds",
        "lat":                    14.8000,
        "lon":                    74.0800,
        "depth":                  20,
        "depth_m":                20,
        "species":                "Mackerel, Sardine, Sciaenids",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 6,
        "advisory":               "Sheltered bay waters with intense nearshore pelagic shoaling.",
        "region":                 "Karnataka",
        "best_season":            "Sep–Dec",
    },
    {
        "id":                     "PFZ-KA-016",
        "zone_id":                "PFZ-KA-016",
        "name":                   "Panambur / New Mangalore Port Shelf",
        "lat":                    12.9400,
        "lon":                    74.7200,
        "depth":                  30,
        "depth_m":                30,
        "species":                "Seer Fish, Trevally, Squid",
        "status":                 "MEDIUM",
        "quality":                "MEDIUM",
        "distance_from_shore_km": 9,
        "advisory":               "Maintain clearance from commercial navigation fairway channels.",
        "region":                 "Karnataka",
        "best_season":            "Oct–Mar",
    },

    # ═════════════════════════════════════════════════════════════════════════
    # 2. KERALA COAST (Kochi, Kozhikode, Kannur, Kollam, Vizhinjam, Ponnani)
    # ═════════════════════════════════════════════════════════════════════════
    {
        "id":                     "PFZ-KL-001",
        "zone_id":                "PFZ-KL-001",
        "name":                   "Kochi Offshore Upwelling Zone",
        "lat":                    9.7200,
        "lon":                    75.8200,
        "depth":                  38,
        "depth_m":                38,
        "species":                "Indian Mackerel, Oil Sardine, Skipjack Tuna",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 18,
        "advisory":               "Strong coastal upwelling. High chlorophyll band SW of Kochi.",
        "region":                 "Kerala",
        "best_season":            "Jun–Sep",
    },
    {
        "id":                     "PFZ-KL-002",
        "zone_id":                "PFZ-KL-002",
        "name":                   "Thiruvananthapuram Deep Water Zone",
        "lat":                    8.3000,
        "lon":                    76.5000,
        "depth":                  60,
        "depth_m":                60,
        "species":                "Seer Fish, Yellow-fin Tuna, Barracuda",
        "status":                 "MEDIUM",
        "quality":                "MEDIUM",
        "distance_from_shore_km": 22,
        "advisory":               "Moderate productivity. Thermocline at 40 m depth.",
        "region":                 "Kerala",
        "best_season":            "Nov–Mar",
    },
    {
        "id":                     "PFZ-KL-003",
        "zone_id":                "PFZ-KL-003",
        "name":                   "Kozhikode–Kannur Continental Shelf",
        "lat":                    11.5000,
        "lon":                    75.5200,
        "depth":                  45,
        "depth_m":                45,
        "species":                "Oil Sardine, Indian Mackerel, Ribbon Fish",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 15,
        "advisory":               "Dense surface shoals reported. Best trawl window: 0500–1100 hrs.",
        "region":                 "Kerala",
        "best_season":            "Jul–Oct",
    },
    {
        "id":                     "PFZ-KL-004",
        "zone_id":                "PFZ-KL-004",
        "name":                   "Lakshadweep Sea Deep-Sea Corridor",
        "lat":                    10.0000,
        "lon":                    74.5000,
        "depth":                  1200,
        "depth_m":                1200,
        "species":                "Yellow-fin Tuna, Big-eye Tuna, Swordfish",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 120,
        "advisory":               "Deep-sea zone. Requires licensed deep-sea vessel.",
        "region":                 "Kerala",
        "best_season":            "Jan–May",
    },
    {
        "id":                     "PFZ-KL-005",
        "zone_id":                "PFZ-KL-005",
        "name":                   "Munambam / Azhikode Offshore Shelf",
        "lat":                    10.1800,
        "lon":                    75.9800,
        "depth":                  32,
        "depth_m":                32,
        "species":                "Karikkadi Shrimp, Threadfin Bream, Cuttlefish",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 16,
        "advisory":               "Prime trawl grounds for Munambam mechanized fleet.",
        "region":                 "Kerala",
        "best_season":            "Aug–Feb",
    },
    {
        "id":                     "PFZ-KL-006",
        "zone_id":                "PFZ-KL-006",
        "name":                   "Kozhikode Beypore Roadstead Bank",
        "lat":                    11.1800,
        "lon":                    75.7200,
        "depth":                  28,
        "depth_m":                28,
        "species":                "Sole Fish, Silver Belly, Mackerel",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 10,
        "advisory":               "Chaliyar river mouth confluence. Rich post-monsoon mud banks (Chakara).",
        "region":                 "Kerala",
        "best_season":            "Jun–Nov",
    },
    {
        "id":                     "PFZ-KL-007",
        "zone_id":                "PFZ-KL-007",
        "name":                   "Kannur Ayikkara Inshore Grounds",
        "lat":                    11.8500,
        "lon":                    75.3000,
        "depth":                  24,
        "depth_m":                24,
        "species":                "Oil Sardine, Blue Crab, Anchovy",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 8,
        "advisory":               "High seasonal pelagic concentration near Mopla bay.",
        "region":                 "Kerala",
        "best_season":            "Jul–Dec",
    },
    {
        "id":                     "PFZ-KL-008",
        "zone_id":                "PFZ-KL-008",
        "name":                   "Thalassery Coastal Bank",
        "lat":                    11.7200,
        "lon":                    75.4200,
        "depth":                  26,
        "depth_m":                26,
        "species":                "Indian Mackerel, White Sardine, Shrimp",
        "status":                 "MEDIUM",
        "quality":                "MEDIUM",
        "distance_from_shore_km": 9,
        "advisory":               "Traditional motorized fiber craft zone.",
        "region":                 "Kerala",
        "best_season":            "Aug–Jan",
    },
    {
        "id":                     "PFZ-KL-009",
        "zone_id":                "PFZ-KL-009",
        "name":                   "Kollam Neendakara Deep Upwelling Bank",
        "lat":                    8.9200,
        "lon":                    76.4500,
        "depth":                  50,
        "depth_m":                50,
        "species":                "Deep Sea Shrimp, Squid, Lizardfish, Snapper",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 15,
        "advisory":               "Major trawling hub. Outstanding shrimp catch rates.",
        "region":                 "Kerala",
        "best_season":            "Aug–Mar",
    },
    {
        "id":                     "PFZ-KL-010",
        "zone_id":                "PFZ-KL-010",
        "name":                   "Kollam Ashtamudi Estuarine Shelf",
        "lat":                    8.8600,
        "lon":                    76.4800,
        "depth":                  28,
        "depth_m":                28,
        "species":                "Clams, Ribbon Fish, Seer Fish",
        "status":                 "MEDIUM",
        "quality":                "MEDIUM",
        "distance_from_shore_km": 11,
        "advisory":               "Rich nutrient discharge from Ashtamudi lake estuary.",
        "region":                 "Kerala",
        "best_season":            "Sep–Feb",
    },
    {
        "id":                     "PFZ-KL-011",
        "zone_id":                "PFZ-KL-011",
        "name":                   "Vizhinjam Deep Pelagic Canyon",
        "lat":                    8.3500,
        "lon":                    76.8800,
        "depth":                  250,
        "depth_m":                250,
        "species":                "Yellow-fin Tuna, Sailfish, Marlin, Dolphin Fish",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 14,
        "advisory":               "Immediate shelf drop-off. Exceptional sport and commercial pelagics.",
        "region":                 "Kerala",
        "best_season":            "Sep–Apr",
    },
    {
        "id":                     "PFZ-KL-012",
        "zone_id":                "PFZ-KL-012",
        "name":                   "Ponnani Estuarine Trawl Ground",
        "lat":                    10.7800,
        "lon":                    75.8200,
        "depth":                  22,
        "depth_m":                22,
        "species":                "Tiger Prawn, Mackerel, Catfish",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 9,
        "advisory":               "Bharathapuzha river outflow provides continuous nutrient enrichment.",
        "region":                 "Kerala",
        "best_season":            "Jul–Dec",
    },

    # ═════════════════════════════════════════════════════════════════════════
    # 3. MAHARASHTRA & GOA COAST (Mumbai, Ratnagiri, Malvan, Alibaug, Vasco, Panaji)
    # ═════════════════════════════════════════════════════════════════════════
    {
        "id":                     "PFZ-GA-001",
        "zone_id":                "PFZ-GA-001",
        "name":                   "Vasco Mormugao Bay Shelf",
        "lat":                    15.3800,
        "lon":                    73.7200,
        "depth":                  28,
        "depth_m":                28,
        "species":                "Squid, Pomfret, Kingfish, Mackerel",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 10,
        "advisory":               "Sheltered waters outside Mormugao port limit.",
        "region":                 "Goa",
        "best_season":            "Sep–Feb",
    },
    {
        "id":                     "PFZ-GA-002",
        "zone_id":                "PFZ-GA-002",
        "name":                   "Panaji Mandovi Offshore Corridor",
        "lat":                    15.5200,
        "lon":                    73.6800,
        "depth":                  32,
        "depth_m":                32,
        "species":                "Silver Pomfret, Indian Mackerel, Crab",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 14,
        "advisory":               "Mandovi-Zuari twin estuarine nutrient plume.",
        "region":                 "Goa",
        "best_season":            "Oct–Mar",
    },
    {
        "id":                     "PFZ-GA-003",
        "zone_id":                "PFZ-GA-003",
        "name":                   "Aguada Coastal Pelagic Shoal",
        "lat":                    15.4800,
        "lon":                    73.7300,
        "depth":                  22,
        "depth_m":                22,
        "species":                "Sardine, Anchovy, Croaker",
        "status":                 "MEDIUM",
        "quality":                "MEDIUM",
        "distance_from_shore_km": 6,
        "advisory":               "Artisanal shoreline seine and motorized craft ground.",
        "region":                 "Goa",
        "best_season":            "Sep–Dec",
    },
    {
        "id":                     "PFZ-MH-001",
        "zone_id":                "PFZ-MH-001",
        "name":                   "Mumbai Offshore Pomfret Zone",
        "lat":                    18.9200,
        "lon":                    72.4200,
        "depth":                  30,
        "depth_m":                30,
        "species":                "Silver Pomfret, Bombay Duck, Ribbon Fish",
        "status":                 "MEDIUM",
        "quality":                "MEDIUM",
        "distance_from_shore_km": 20,
        "advisory":               "Active zone but high vessel traffic. Monitor AIS before entry.",
        "region":                 "Maharashtra",
        "best_season":            "Nov–Feb",
    },
    {
        "id":                     "PFZ-MH-002",
        "zone_id":                "PFZ-MH-002",
        "name":                   "Ratnagiri Shelf Edge Zone",
        "lat":                    16.8200,
        "lon":                    72.7800,
        "depth":                  65,
        "depth_m":                65,
        "species":                "Yellow-fin Tuna, Seer Fish, Mackerel",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 28,
        "advisory":               "Shelf-edge upwelling. Historically highest yield in Konkan region.",
        "region":                 "Maharashtra",
        "best_season":            "Oct–Mar",
    },
    {
        "id":                     "PFZ-MH-003",
        "zone_id":                "PFZ-MH-003",
        "name":                   "Malvan Coastal Reef Zone",
        "lat":                    15.7000,
        "lon":                    73.4200,
        "depth":                  22,
        "depth_m":                22,
        "species":                "Grouper, Snapper, Crab",
        "status":                 "MEDIUM",
        "quality":                "MEDIUM",
        "distance_from_shore_km": 12,
        "advisory":               "Reef area — use line fishing; bottom trawling restricted.",
        "region":                 "Maharashtra",
        "best_season":            "Nov–Mar",
    },
    {
        "id":                     "PFZ-MH-004",
        "zone_id":                "PFZ-MH-004",
        "name":                   "Mumbai Sassoon Dock Southern Bank",
        "lat":                    18.8500,
        "lon":                    72.7000,
        "depth":                  24,
        "depth_m":                24,
        "species":                "Penaeid Prawns, Jewfish, Bombay Duck",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 14,
        "advisory":               "Extremely high commercial landing concentration.",
        "region":                 "Maharashtra",
        "best_season":            "Sep–Jan",
    },
    {
        "id":                     "PFZ-MH-005",
        "zone_id":                "PFZ-MH-005",
        "name":                   "Versova Pelagic Trawl Ground",
        "lat":                    19.1400,
        "lon":                    72.6800,
        "depth":                  26,
        "depth_m":                26,
        "species":                "Bombay Duck, Golden Anchovy, Prawns",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 12,
        "advisory":               "Traditional Koli fishing grounds. High tidal drift.",
        "region":                 "Maharashtra",
        "best_season":            "Oct–Feb",
    },
    {
        "id":                     "PFZ-MH-006",
        "zone_id":                "PFZ-MH-006",
        "name":                   "Alibaug Rewas Coastal Shoal",
        "lat":                    18.7200,
        "lon":                    72.7500,
        "depth":                  18,
        "depth_m":                18,
        "species":                "Mud Crab, Mullet, White Sardine",
        "status":                 "MEDIUM",
        "quality":                "MEDIUM",
        "distance_from_shore_km": 8,
        "advisory":               "Shallow estuarine bank off Dharamtar creek mouth.",
        "region":                 "Maharashtra",
        "best_season":            "Oct–Jan",
    },
    {
        "id":                     "PFZ-MH-007",
        "zone_id":                "PFZ-MH-007",
        "name":                   "Murud Janjira Deep Corridor",
        "lat":                    18.2800,
        "lon":                    72.8200,
        "depth":                  35,
        "depth_m":                35,
        "species":                "Kingfish, Black Pomfret, Squid",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 16,
        "advisory":               "Rocky reef edge drop-off. Outstanding seer fish catch.",
        "region":                 "Maharashtra",
        "best_season":            "Nov–Mar",
    },
    {
        "id":                     "PFZ-MH-008",
        "zone_id":                "PFZ-MH-008",
        "name":                   "Ratnagiri Mirya Bay Upwelling Ground",
        "lat":                    17.0200,
        "lon":                    73.1800,
        "depth":                  32,
        "depth_m":                32,
        "species":                "Mackerel, Sardine, Scad",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 12,
        "advisory":               "Intense post-monsoon chlorophyll aggregation.",
        "region":                 "Maharashtra",
        "best_season":            "Sep–Dec",
    },
    {
        "id":                     "PFZ-MH-009",
        "zone_id":                "PFZ-MH-009",
        "name":                   "Vengurla Rocks Pelagic Corridor",
        "lat":                    15.8800,
        "lon":                    73.5500,
        "depth":                  40,
        "depth_m":                40,
        "species":                "Cobia, Sailfish, Seer Fish, Squid",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 15,
        "advisory":               "Clear waters around Burnt Islands. Excellent trolling.",
        "region":                 "Maharashtra",
        "best_season":            "Oct–Apr",
    },

    # ═════════════════════════════════════════════════════════════════════════
    # 4. GUJARAT COAST (Veraval, Porbandar, Okha, Mangrol, Jakhau)
    # ═════════════════════════════════════════════════════════════════════════
    {
        "id":                     "PFZ-GJ-001",
        "zone_id":                "PFZ-GJ-001",
        "name":                   "Veraval–Porbandar Productive Corridor",
        "lat":                    21.0000,
        "lon":                    69.8200,
        "depth":                  40,
        "depth_m":                40,
        "species":                "Bombay Duck, Shrimp, Pomfret",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 20,
        "advisory":               "One of India's richest zones. High seasonal CPUE.",
        "region":                 "Gujarat",
        "best_season":            "Sep–Jan",
    },
    {
        "id":                     "PFZ-GJ-002",
        "zone_id":                "PFZ-GJ-002",
        "name":                   "Gulf of Kutch Northern Zone",
        "lat":                    22.5000,
        "lon":                    69.0200,
        "depth":                  15,
        "depth_m":                15,
        "species":                "Hilsa, Mullet, Anchovy",
        "status":                 "MEDIUM",
        "quality":                "MEDIUM",
        "distance_from_shore_km": 12,
        "advisory":               "Tidal currents strong. Fishing window limited to slack tide.",
        "region":                 "Gujarat",
        "best_season":            "Oct–Dec",
    },
    {
        "id":                     "PFZ-GJ-003",
        "zone_id":                "PFZ-GJ-003",
        "name":                   "Veraval Somnath Harbor Inshore Shelf",
        "lat":                    20.8800,
        "lon":                    70.3200,
        "depth":                  30,
        "depth_m":                30,
        "species":                "Silver Pomfret, Ribbon Fish, Cuttlefish",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 10,
        "advisory":               "India's largest mechanized fish landing hub.",
        "region":                 "Gujarat",
        "best_season":            "Sep–Mar",
    },
    {
        "id":                     "PFZ-GJ-004",
        "zone_id":                "PFZ-GJ-004",
        "name":                   "Porbandar Deep Sea Trawl Grounds",
        "lat":                    21.6200,
        "lon":                    69.4200,
        "depth":                  52,
        "depth_m":                52,
        "species":                "Tuna, Ribbon Fish, Tiger Prawn, Threadfin Bream",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 22,
        "advisory":               "Wide continental shelf. Heavy gillnet and trawl fleets.",
        "region":                 "Gujarat",
        "best_season":            "Sep–Feb",
    },
    {
        "id":                     "PFZ-GJ-005",
        "zone_id":                "PFZ-GJ-005",
        "name":                   "Okha Gateway Pelagic Corridor",
        "lat":                    22.4800,
        "lon":                    68.9500,
        "depth":                  35,
        "depth_m":                35,
        "species":                "Ghol, Lobster, Shark, Kingfish",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 15,
        "advisory":               "Mouth of Kutch Gulf. Strong tidal currents; caution required.",
        "region":                 "Gujarat",
        "best_season":            "Oct–Mar",
    },
    {
        "id":                     "PFZ-GJ-006",
        "zone_id":                "PFZ-GJ-006",
        "name":                   "Dwarka Continental Shelf Bank",
        "lat":                    22.2200,
        "lon":                    68.8500,
        "depth":                  45,
        "depth_m":                45,
        "species":                "Hilsa, Pomfret, Ribbon Fish",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 18,
        "advisory":               "Rich nutrient mixing from Gulf outflow.",
        "region":                 "Gujarat",
        "best_season":            "Oct–Feb",
    },
    {
        "id":                     "PFZ-GJ-007",
        "zone_id":                "PFZ-GJ-007",
        "name":                   "Mangrol Harbor Coastal Ground",
        "lat":                    21.1100,
        "lon":                    70.0200,
        "depth":                  25,
        "depth_m":                25,
        "species":                "Croaker, Catfish, White Shrimp",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 8,
        "advisory":               "Consistent nearshore trawl ground. Early morning best.",
        "region":                 "Gujarat",
        "best_season":            "Sep–Jan",
    },
    {
        "id":                     "PFZ-GJ-008",
        "zone_id":                "PFZ-GJ-008",
        "name":                   "Chorwad Upwelling Bank",
        "lat":                    21.0100,
        "lon":                    70.1800,
        "depth":                  28,
        "depth_m":                28,
        "species":                "Pomfret, Mackerel, Eel",
        "status":                 "MEDIUM",
        "quality":                "MEDIUM",
        "distance_from_shore_km": 11,
        "advisory":               "Moderate productivity coastal upwelling cell.",
        "region":                 "Gujarat",
        "best_season":            "Oct–Feb",
    },
    {
        "id":                     "PFZ-GJ-009",
        "zone_id":                "PFZ-GJ-009",
        "name":                   "Jakhau Outer Kutch Shelf",
        "lat":                    23.2000,
        "lon":                    68.4500,
        "depth":                  22,
        "depth_m":                22,
        "species":                "Prawn, Pomfret, Hilsa, Sea Bream",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 16,
        "advisory":               "Proximity to IMBL; strict GPS watch required.",
        "region":                 "Gujarat",
        "best_season":            "Sep–Feb",
    },
    {
        "id":                     "PFZ-GJ-010",
        "zone_id":                "PFZ-GJ-010",
        "name":                   "Kori Creek Estuarine Zone",
        "lat":                    23.4500,
        "lon":                    68.3200,
        "depth":                  12,
        "depth_m":                12,
        "species":                "Mud Prawn, Catfish, Mullet",
        "status":                 "LOW",
        "quality":                "LOW",
        "distance_from_shore_km": 7,
        "advisory":               "Border creek zone. Authorized artisanal vessels only.",
        "region":                 "Gujarat",
        "best_season":            "Nov–Jan",
    },

    # ═════════════════════════════════════════════════════════════════════════
    # 5. TAMIL NADU & EAST COAST (Rameswaram, Chennai, Cuddalore, Tuticorin, Vizag, Paradip, Digha)
    # ═════════════════════════════════════════════════════════════════════════
    {
        "id":                     "PFZ-TN-001",
        "zone_id":                "PFZ-TN-001",
        "name":                   "Rameswaram Palk Strait Zone",
        "lat":                    9.1500,
        "lon":                    79.6500,
        "depth":                  12,
        "depth_m":                12,
        "species":                "Prawns, Cuttlefish, Reef Fish",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 8,
        "advisory":               "Shallow-water zone. Monitor IMBL proximity strictly.",
        "region":                 "Tamil Nadu",
        "best_season":            "Nov–Mar",
    },
    {
        "id":                     "PFZ-TN-002",
        "zone_id":                "PFZ-TN-002",
        "name":                   "Tuticorin Gulf of Mannar Zone",
        "lat":                    8.7500,
        "lon":                    78.4000,
        "depth":                  25,
        "depth_m":                25,
        "species":                "Pearl Spot, Sea Cucumber, Lobster",
        "status":                 "MEDIUM",
        "quality":                "MEDIUM",
        "distance_from_shore_km": 14,
        "advisory":               "Marine protected area boundary nearby.",
        "region":                 "Tamil Nadu",
        "best_season":            "Oct–Feb",
    },
    {
        "id":                     "PFZ-TN-003",
        "zone_id":                "PFZ-TN-003",
        "name":                   "Nagapattinam Bay of Bengal Shelf",
        "lat":                    11.0000,
        "lon":                    80.2200,
        "depth":                  35,
        "depth_m":                35,
        "species":                "Catfish, Shrimp, Pomfret",
        "status":                 "MEDIUM",
        "quality":                "MEDIUM",
        "distance_from_shore_km": 20,
        "advisory":               "Moderate chlorophyll post-monsoon.",
        "region":                 "Tamil Nadu",
        "best_season":            "Dec–Feb",
    },
    {
        "id":                     "PFZ-TN-004",
        "zone_id":                "PFZ-TN-004",
        "name":                   "Chennai–Ennore Nearshore Zone",
        "lat":                    13.3200,
        "lon":                    80.5000,
        "depth":                  20,
        "depth_m":                20,
        "species":                "Mullet, Anchovy, Needlefish",
        "status":                 "LOW",
        "quality":                "LOW",
        "distance_from_shore_km": 10,
        "advisory":               "Port industrial fairway. Exercise caution.",
        "region":                 "Tamil Nadu",
        "best_season":            "Jan–Mar only",
    },
    {
        "id":                     "PFZ-TN-005",
        "zone_id":                "PFZ-TN-005",
        "name":                   "Chennai Kasimedu / Royapuram Harbor Shelf",
        "lat":                    13.1200,
        "lon":                    80.3800,
        "depth":                  28,
        "depth_m":                28,
        "species":                "Seer Fish, Trevally, Tuna, Prawns",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 9,
        "advisory":               "Kasimedu major landing center. High offshore pelagic aggregation.",
        "region":                 "Tamil Nadu",
        "best_season":            "Dec–Apr",
    },
    {
        "id":                     "PFZ-TN-006",
        "zone_id":                "PFZ-TN-006",
        "name":                   "Cuddalore Silver Beach Pelagic Zone",
        "lat":                    11.7500,
        "lon":                    79.8800,
        "depth":                  30,
        "depth_m":                30,
        "species":                "Seer Fish, Ribbon Fish, Squid",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 12,
        "advisory":               "Gadilam and Uppanar river confluence grounds.",
        "region":                 "Tamil Nadu",
        "best_season":            "Nov–Mar",
    },
    {
        "id":                     "PFZ-TN-007",
        "zone_id":                "PFZ-TN-007",
        "name":                   "Porto Novo / Parangipettai Continental Shelf",
        "lat":                    11.5000,
        "lon":                    79.9200,
        "depth":                  34,
        "depth_m":                34,
        "species":                "Crab, Sole Fish, White Shrimp, Pomfret",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 14,
        "advisory":               "Vellar estuary mangrove outflow enriches continental shelf.",
        "region":                 "Tamil Nadu",
        "best_season":            "Dec–Mar",
    },
    {
        "id":                     "PFZ-TN-008",
        "zone_id":                "PFZ-TN-008",
        "name":                   "Mandapam Southern Palk Bay Shelf",
        "lat":                    9.2500,
        "lon":                    79.1800,
        "depth":                  14,
        "depth_m":                14,
        "species":                "Crab, Squid, Sardine, Snapper",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 7,
        "advisory":               "Calm sheltered bay with high benthic and seagrass productivity.",
        "region":                 "Tamil Nadu",
        "best_season":            "May–Oct",
    },
    {
        "id":                     "PFZ-TN-009",
        "zone_id":                "PFZ-TN-009",
        "name":                   "Tiruchendur Pearl Reef Bank",
        "lat":                    8.5000,
        "lon":                    78.2200,
        "depth":                  22,
        "depth_m":                22,
        "species":                "Carangids, Snapper, Barracuda",
        "status":                 "MEDIUM",
        "quality":                "MEDIUM",
        "distance_from_shore_km": 10,
        "advisory":               "Rocky reef edge. Excellent hook-and-line fishing.",
        "region":                 "Tamil Nadu",
        "best_season":            "Nov–Feb",
    },
    {
        "id":                     "PFZ-AP-001",
        "zone_id":                "PFZ-AP-001",
        "name":                   "Visakhapatnam Bay of Bengal Upwelling",
        "lat":                    17.5200,
        "lon":                    83.7200,
        "depth":                  55,
        "depth_m":                55,
        "species":                "Yellow-fin Tuna, Seer Fish, Prawns",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 22,
        "advisory":               "Consistent upwelling near submarine canyon. Best yields Oct–Jan.",
        "region":                 "Andhra Pradesh",
        "best_season":            "Oct–Jan",
    },
    {
        "id":                     "PFZ-AP-002",
        "zone_id":                "PFZ-AP-002",
        "name":                   "Kakinada Offshore Delta Zone",
        "lat":                    16.8200,
        "lon":                    82.5000,
        "depth":                  35,
        "depth_m":                35,
        "species":                "Prawns, Catfish, Mullet",
        "status":                 "MEDIUM",
        "quality":                "MEDIUM",
        "distance_from_shore_km": 18,
        "advisory":               "River outflow enriches zone post-monsoon. Peak: Nov–Feb.",
        "region":                 "Andhra Pradesh",
        "best_season":            "Nov–Feb",
    },
    {
        "id":                     "PFZ-AP-003",
        "zone_id":                "PFZ-AP-003",
        "name":                   "Gangavaram Deep Trench Corridor",
        "lat":                    17.6000,
        "lon":                    83.4500,
        "depth":                  90,
        "depth_m":                90,
        "species":                "Bigeye Tuna, Marlin, Swordfish",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 26,
        "advisory":               "Deep drop-off beyond port limit. Deep-sea longlining recommended.",
        "region":                 "Andhra Pradesh",
        "best_season":            "Nov–Apr",
    },
    {
        "id":                     "PFZ-AP-004",
        "zone_id":                "PFZ-AP-004",
        "name":                   "Kakinada Hope Island Upwelling Corridor",
        "lat":                    16.9200,
        "lon":                    82.3800,
        "depth":                  22,
        "depth_m":                22,
        "species":                "Hilsa, Indian White Prawn, Threadfin",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 8,
        "advisory":               "Coringa mangrove spit creates exceptional feeding grounds.",
        "region":                 "Andhra Pradesh",
        "best_season":            "Oct–Mar",
    },
    {
        "id":                     "PFZ-OD-001",
        "zone_id":                "PFZ-OD-001",
        "name":                   "Paradip Offshore Continental Shelf",
        "lat":                    20.0800,
        "lon":                    87.0000,
        "depth":                  45,
        "depth_m":                45,
        "species":                "Hilsa, Prawns, Pomfret",
        "status":                 "MEDIUM",
        "quality":                "MEDIUM",
        "distance_from_shore_km": 20,
        "advisory":               "Mahanadi plume creates nutrient-rich patch post-monsoon.",
        "region":                 "Odisha",
        "best_season":            "Oct–Feb",
    },
    {
        "id":                     "PFZ-OD-002",
        "zone_id":                "PFZ-OD-002",
        "name":                   "Chilika Lake Outlet Estuarine Zone",
        "lat":                    19.5200,
        "lon":                    85.5500,
        "depth":                  8,
        "depth_m":                8,
        "species":                "Mullet, Prawn, Crab",
        "status":                 "LOW",
        "quality":                "LOW",
        "distance_from_shore_km": 5,
        "advisory":               "Very shallow. Small traditional craft only. Rich estuarine biodiversity.",
        "region":                 "Odisha",
        "best_season":            "Dec–Feb",
    },
    {
        "id":                     "PFZ-OD-003",
        "zone_id":                "PFZ-OD-003",
        "name":                   "Paradip Mahanadi Mouth Marine Ground",
        "lat":                    20.2800,
        "lon":                    86.8200,
        "depth":                  26,
        "depth_m":                26,
        "species":                "Hilsa, Ribbon Fish, Catfish, Croaker",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 11,
        "advisory":               "Major estuarine plume. Heavy concentrations of Hilsa shoals.",
        "region":                 "Odisha",
        "best_season":            "Sep–Jan",
    },
    {
        "id":                     "PFZ-WB-001",
        "zone_id":                "PFZ-WB-001",
        "name":                   "Sundarbans–Haldia Bay of Bengal Zone",
        "lat":                    21.6200,
        "lon":                    88.1800,
        "depth":                  18,
        "depth_m":                18,
        "species":                "Hilsa, Tiger Prawn, Anchovy",
        "status":                 "MEDIUM",
        "quality":                "MEDIUM",
        "distance_from_shore_km": 15,
        "advisory":               "Ganges outflow creates seasonal nursery ground. Cyclone risk Jun–Nov.",
        "region":                 "West Bengal",
        "best_season":            "Feb–May",
    },
    {
        "id":                     "PFZ-WB-002",
        "zone_id":                "PFZ-WB-002",
        "name":                   "Digha Shankarpur Trawl Ground",
        "lat":                    21.5500,
        "lon":                    87.6200,
        "depth":                  20,
        "depth_m":                20,
        "species":                "Silver Pomfret, Hilsa, Tiger Prawn, Ribbon Fish",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 12,
        "advisory":               "Premier marine fish landing center of West Bengal.",
        "region":                 "West Bengal",
        "best_season":            "Aug–Feb",
    },
    {
        "id":                     "PFZ-WB-003",
        "zone_id":                "PFZ-WB-003",
        "name":                   "Junput Coastal Trawl Shelf",
        "lat":                    21.6800,
        "lon":                    87.8200,
        "depth":                  16,
        "depth_m":                16,
        "species":                "Hilsa, Bombay Duck, Anchovy",
        "status":                 "MEDIUM",
        "quality":                "MEDIUM",
        "distance_from_shore_km": 8,
        "advisory":               "Shallow coastal mudflat zone. High artisanal bagnet CPUE.",
        "region":                 "West Bengal",
        "best_season":            "Sep–Jan",
    },
    {
        "id":                     "PFZ-AN-001",
        "zone_id":                "PFZ-AN-001",
        "name":                   "Andaman Sea Tuna Aggregation Zone",
        "lat":                    11.5000,
        "lon":                    93.0000,
        "depth":                  800,
        "depth_m":                800,
        "species":                "Yellow-fin Tuna, Bigeye Tuna, Mahi-mahi",
        "status":                 "HIGH",
        "quality":                "HIGH",
        "distance_from_shore_km": 35,
        "advisory":               "International-grade tuna fishery. Export-quality catch. Deep-sea vessel required.",
        "region":                 "Andaman & Nicobar Islands",
        "best_season":            "Jan–Apr",
    },
]


# ─────────────────────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────────────────────

def get_all_zones() -> list[dict]:
    """Return the complete PFZ database (read-only copy)."""
    return list(PFZ_DATABASE)   # shallow copy — safe since dicts are not mutated


def find_nearest_zones(
    user_lat: float,
    user_lon: float,
    max_results: int = 5,
    max_distance_km: float = 400.0,
) -> list[dict]:
    """
    Find the closest PFZ zones to a given GPS position.

    Each returned zone dict has one extra key added:
        "distance_to_user_km" (float): great-circle distance from user to zone centroid.

    Zones beyond max_distance_km are excluded so that a Kochi user does not
    see Andaman zones in their top-5 list.

    Args:
        user_lat         : User / vessel latitude (decimal degrees).
        user_lon         : User / vessel longitude (decimal degrees).
        max_results      : Maximum number of zones to return (default 5).
        max_distance_km  : Hard cutoff — zones further than this are ignored.

    Returns:
        List of zone dicts sorted by ascending distance_to_user_km.
        May be empty if no zones exist within max_distance_km.
    """
    enriched = []
    for zone in PFZ_DATABASE:
        dist = haversine_km(user_lat, user_lon, zone["lat"], zone["lon"])
        if dist <= max_distance_km:
            enriched.append({**zone, "distance_to_user_km": round(dist, 1)})

    enriched.sort(key=lambda z: z["distance_to_user_km"])
    return enriched[:max_results]


def to_geojson(zones: list[dict]) -> dict:
    """
    Convert a list of PFZ zone dicts to a GeoJSON FeatureCollection.

    Useful for future integration with QGIS, Mapbox, or INCOIS data feeds.

    Args:
        zones: List of zone dicts (as returned by find_nearest_zones or get_all_zones).

    Returns:
        GeoJSON FeatureCollection dict.
    """
    features = [
        {
            "type": "Feature",
            "geometry": {
                "type":        "Point",
                "coordinates": [z["lon"], z["lat"]],  # GeoJSON: [lon, lat]
            },
            "properties": {k: v for k, v in z.items() if k not in ("lat", "lon")},
        }
        for z in zones
    ]
    return {"type": "FeatureCollection", "features": features}
